#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script de traduction automatique du README français vers anglais
"""

import re

def translate_readme():
    # Dictionnaire de traductions
    translations = {
        # Headers
        "Méthode Recommandée - Démarrage Automatique": "Recommended Method - Automatic Startup",
        "Test Complet - Démarrage Manuel des Services": "Complete Test - Manual Service Startup", 
        "Tester le Jeu Cosmo": "Test Cosmo Game",
        "Tester le Chatbot IA": "Test AI Chatbot",
        "Tester le Dashboard ML": "Test ML Dashboard",
        "Tester l'API ML": "Test ML API",
        "Scripts de Test Automatisés": "Automated Test Scripts",
        "Guides d'Utilisation Spécifiques": "Specific Usage Guides",
        "Guide du Jeu Cosmo": "Cosmo Game Guide",
        "Guide du Chatbot": "Chatbot Guide",
        "Guide du Dashboard": "Dashboard Guide",
        "Dépannage": "Troubleshooting",
        "Problèmes Courants": "Common Issues",
        "Logs et Debug": "Logs and Debug",
        "Performance et Métriques": "Performance and Metrics",
        "Métriques du Système": "System Metrics",
        "Optimisations": "Optimizations",
        "Déploiement Production": "Production Deployment",
        "Configuration Production": "Production Configuration",
        "Contribution": "Contribution",
        "Comment Contribuer": "How to Contribute",
        "Standards de Code": "Code Standards",
        "Roadmap": "Roadmap",
        "Version 2.0 (Planifiée)": "Version 2.0 (Planned)",
        "Fonctionnalités Avancées": "Advanced Features",
        "Support et Contact": "Support and Contact",
        "Obtenir de l'Aide": "Getting Help",
        "Communauté": "Community",
        "Licence": "License",
        "Remerciements": "Acknowledgments",
        
        # Content
        "Test complet de l'environnement": "Complete environment test",
        "Démarrage de tous les services": "Start all services",
        "Ouvre automatiquement toutes les interfaces dans le navigateur": "Automatically opens all interfaces in browser",
        "Arrêt propre (quand terminé)": "Clean shutdown (when finished)",
        "Cette méthode démarre automatiquement": "This method automatically starts",
        "Ouvre les interfaces web dans le navigateur": "Opens web interfaces in browser",
        "Tests automatisés": "Automated tests",
        "Serveur local simple": "Simple local server",
        "Directement dans le navigateur": "Directly in browser",
        "Fonctionnalités à tester": "Features to test",
        "Menu principal et navigation": "Main menu and navigation",
        "Scan de planètes dans la carte galactique": "Planet scanning in galactic map",
        "Quiz multi-niveaux": "Multi-level quiz",
        "Système solaire interactif": "Interactive solar system",
        "Progression XP et récompenses": "XP progression and rewards",
        "Interface Web": "Web Interface",
        "Démarrer les backends": "Start backends",
        "Ouvrir l'interface de test": "Open test interface",
        "Version Terminal": "Terminal Version",
        "Taper des questions en français ou anglais": "Type questions in French or English",
        "Tests API Directs": "Direct API Tests",
        "Test simple": "Simple test",
        "Test avec données ML": "Test with ML data",
        "Démarrer Streamlit": "Start Streamlit",
        "Exemples prédéfinis": "Predefined examples",
        "Saisie manuelle de paramètres": "Manual parameter input",
        "Génération de valeurs aléatoires": "Random value generation",
        "Visualisations interactives": "Interactive visualizations",
        "Graphiques radar de profil": "Radar charts for profiles",
        "Test direct de l'API Flask": "Direct Flask API test",
        "Résultat attendu": "Expected result",
        "Test Rapide Global": "Quick Global Test",
        "Tests Manuels Détaillés": "Detailed Manual Tests",
        "Test des dépendances": "Dependency test",
        "Toutes les dépendances sont installées": "All dependencies are installed",
        "Test du modèle ML": "ML model test",
        "Modèle ML chargé avec succès": "ML model loaded successfully",
        "Questions Simples": "Simple Questions",
        "Salutation": "Greeting",
        "Information générale": "General information",
        "Guide technique": "Technical guide",
        "Analyse ML": "ML Analysis",
        "Remplir les 10 paramètres dans l'interface web": "Fill in the 10 parameters in the web interface",
        "Utiliser les boutons de test rapide": "Use quick test buttons",
        "Observer l'intégration des résultats ML": "Observe ML results integration",
        "Mode Manuel": "Manual Mode",
        "Saisissez vos propres valeurs": "Enter your own values",
        "Exemples": "Examples",
        "Utilisez les cas prédéfinis": "Use predefined cases",
        "Aléatoire": "Random",
        "Générez des données de test": "Generate test data",
        "Analyse": "Analysis",
        "Observez les visualisations et métriques": "Observe visualizations and metrics",
        "Backend ML ne démarre pas": "ML Backend won't start",
        "Solution": "Solution",
        "Régénérer le modèle": "Regenerate model",
        "Vérifier les dépendances": "Check dependencies",
        "Chatbot ne répond pas": "Chatbot not responding",
        "Vérifier que les backends tournent": "Check that backends are running",
        "Redémarrer les services": "Restart services",
        "Dashboard Streamlit ne s'affiche pas": "Streamlit Dashboard not displaying",
        "Installer Streamlit": "Install Streamlit",
        "Démarrer avec debug": "Start with debug",
        "Jeu ne se charge pas": "Game won't load",
        "Ou utiliser un serveur web": "Or use a web server",
        "Logs des backends": "Backend logs",
        "Debug Python": "Python debug",
        "Debug Node.js": "Node.js debug",
        "de précision sur dataset NASA": "accuracy on NASA dataset",
        "Temps de réponse": "Response time",
        "pour prédictions": "for predictions",
        "Support français/anglais": "French/English support",
        "niveaux, 100+ questions astronomie": "levels, 100+ astronomy questions",
        "Modèles ML mis en cache": "ML models cached",
        "Réponses chatbot optimisées": "Optimized chatbot responses",
        "Assets jeu compressés": "Compressed game assets",
        "APIs REST performantes": "High-performance REST APIs",
        "Variables d'environnement": "Environment variables",
        "Services avec PM2": "Services with PM2",
        "optionnel": "optional",
        "Configuration dans": "Configuration in",
        "Dockerfile exemple": "Example Dockerfile",
        "Fork le projet": "Fork the project",
        "Créer une branche": "Create a branch",
        "Ouvrir une Pull Request": "Open a Pull Request",
        "Obligatoires pour nouvelles fonctionnalités": "Required for new features",
        "Planifiée": "Planned",
        "Interface React complète": "Complete React interface",
        "Base de données persistante": "Persistent database",
        "Système d'authentification": "Authentication system",
        "Application mobile": "Mobile application",
        "Support multilingue étendu": "Extended multilingual support",
        "Bande sonore immersive": "Immersive soundtrack",
        "Système de classements": "Ranking system",
        "VR/AR pour exploration spatiale": "VR/AR for space exploration",
        "IA conversationnelle avancée": "Advanced conversational AI",
        "Intégration APIs NASA temps réel": "Real-time NASA API integration",
        "Multijoueur collaboratif": "Collaborative multiplayer",
        "Génération procédurale d'univers": "Procedural universe generation",
        "Consultez ce README et": "Check this README and",
        "Ouvrir une issue GitHub": "Open a GitHub issue",
        "Discussions GitHub": "GitHub Discussions",
        "Voir profil GitHub": "See GitHub profile",
        "Star le projet si il vous plaît": "Star the project if you like it",
        "Fork pour vos modifications": "Fork for your modifications",
        "Partagez avec la communauté": "Share with the community",
        "Ce projet est sous licence MIT. Voir le fichier": "This project is under MIT license. See the",
        "pour plus de détails": "file for more details",
        "Pour les données Kepler publiques": "For public Kepler data",
        "Pour l'API d'intelligence artificielle": "For the artificial intelligence API",
        "Pour les nombreuses bibliothèques utilisées": "For the many libraries used",
        "Pour l'interface dashboard": "For the dashboard interface",
        "Pour les icônes": "For the icons",
        "Explorez l'Univers avec l'IA": "Explore the Universe with AI",
        "Fait avec ❤️ pour l'éducation spatiale": "Made with ❤️ for space education"
    }
    
    # Lire le fichier
    with open('README.md', 'r', encoding='utf-8') as f:
        content = f.read()
    
    # Appliquer les traductions
    for french, english in translations.items():
        content = content.replace(french, english)
    
    # Sauvegarder
    with open('README.md', 'w', encoding='utf-8') as f:
        f.write(content)
    
    print("✅ README traduit avec succès en anglais!")

if __name__ == "__main__":
    translate_readme()
